################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src/Lvgl_Porting \
Core/Src/Lvgl_Ui/custom \
Core/Src/Lvgl_Ui/generated \
Core/Src/Lvgl_Ui/generated/guider_fonts \
Core/Src/Lvgl_Ui/generated/images \
Core/Src/Lvgl_Ui \
Core/Src \
Core/Startup \
Drivers/STM32H7xx_HAL_Driver/Src \
LVGL/lvgl/demos/benchmark/assets \
LVGL/lvgl/demos/benchmark \
LVGL/lvgl/demos/keypad_encoder \
LVGL/lvgl/demos/music/assets \
LVGL/lvgl/demos/music \
LVGL/lvgl/demos/stress \
LVGL/lvgl/demos/widgets/assets \
LVGL/lvgl/demos/widgets \
LVGL/lvgl/env_support/rt-thread \
LVGL/lvgl/env_support/rt-thread/squareline \
LVGL/lvgl/examples/anim \
LVGL/lvgl/examples/assets \
LVGL/lvgl/examples/assets/emoji \
LVGL/lvgl/examples/event \
LVGL/lvgl/examples/get_started \
LVGL/lvgl/examples/layouts/flex \
LVGL/lvgl/examples/layouts/grid \
LVGL/lvgl/examples/libs/bmp \
LVGL/lvgl/examples/libs/ffmpeg \
LVGL/lvgl/examples/libs/freetype \
LVGL/lvgl/examples/libs/gif \
LVGL/lvgl/examples/libs/png \
LVGL/lvgl/examples/libs/qrcode \
LVGL/lvgl/examples/libs/rlottie \
LVGL/lvgl/examples/libs/sjpg \
LVGL/lvgl/examples/others/fragment \
LVGL/lvgl/examples/others/gridnav \
LVGL/lvgl/examples/others/ime \
LVGL/lvgl/examples/others/imgfont \
LVGL/lvgl/examples/others/monkey \
LVGL/lvgl/examples/others/msg \
LVGL/lvgl/examples/others/snapshot \
LVGL/lvgl/examples/porting \
LVGL/lvgl/examples/scroll \
LVGL/lvgl/examples/styles \
LVGL/lvgl/examples/widgets/animimg \
LVGL/lvgl/examples/widgets/arc \
LVGL/lvgl/examples/widgets/bar \
LVGL/lvgl/examples/widgets/btn \
LVGL/lvgl/examples/widgets/btnmatrix \
LVGL/lvgl/examples/widgets/calendar \
LVGL/lvgl/examples/widgets/canvas \
LVGL/lvgl/examples/widgets/chart \
LVGL/lvgl/examples/widgets/checkbox \
LVGL/lvgl/examples/widgets/colorwheel \
LVGL/lvgl/examples/widgets/dropdown \
LVGL/lvgl/examples/widgets/img \
LVGL/lvgl/examples/widgets/imgbtn \
LVGL/lvgl/examples/widgets/keyboard \
LVGL/lvgl/examples/widgets/label \
LVGL/lvgl/examples/widgets/led \
LVGL/lvgl/examples/widgets/line \
LVGL/lvgl/examples/widgets/list \
LVGL/lvgl/examples/widgets/menu \
LVGL/lvgl/examples/widgets/meter \
LVGL/lvgl/examples/widgets/msgbox \
LVGL/lvgl/examples/widgets/obj \
LVGL/lvgl/examples/widgets/roller \
LVGL/lvgl/examples/widgets/slider \
LVGL/lvgl/examples/widgets/span \
LVGL/lvgl/examples/widgets/spinbox \
LVGL/lvgl/examples/widgets/spinner \
LVGL/lvgl/examples/widgets/switch \
LVGL/lvgl/examples/widgets/table \
LVGL/lvgl/examples/widgets/tabview \
LVGL/lvgl/examples/widgets/textarea \
LVGL/lvgl/examples/widgets/tileview \
LVGL/lvgl/examples/widgets/win \
LVGL/lvgl/src/core \
LVGL/lvgl/src/draw/arm2d \
LVGL/lvgl/src/draw \
LVGL/lvgl/src/draw/nxp/pxp \
LVGL/lvgl/src/draw/nxp/vglite \
LVGL/lvgl/src/draw/renesas \
LVGL/lvgl/src/draw/sdl \
LVGL/lvgl/src/draw/stm32_dma2d \
LVGL/lvgl/src/draw/sw \
LVGL/lvgl/src/draw/swm341_dma2d \
LVGL/lvgl/src/extra/layouts/flex \
LVGL/lvgl/src/extra/layouts/grid \
LVGL/lvgl/src/extra/libs/barcode \
LVGL/lvgl/src/extra/libs/bmp \
LVGL/lvgl/src/extra/libs/ffmpeg \
LVGL/lvgl/src/extra/libs/freetype \
LVGL/lvgl/src/extra/libs/fsdrv \
LVGL/lvgl/src/extra/libs/gif \
LVGL/lvgl/src/extra/libs/png \
LVGL/lvgl/src/extra/libs/qrcode \
LVGL/lvgl/src/extra/libs/rlottie \
LVGL/lvgl/src/extra/libs/sjpg \
LVGL/lvgl/src/extra/libs/tiny_ttf \
LVGL/lvgl/src/extra \
LVGL/lvgl/src/extra/others/fragment \
LVGL/lvgl/src/extra/others/gridnav \
LVGL/lvgl/src/extra/others/ime \
LVGL/lvgl/src/extra/others/imgfont \
LVGL/lvgl/src/extra/others/monkey \
LVGL/lvgl/src/extra/others/msg \
LVGL/lvgl/src/extra/others/snapshot \
LVGL/lvgl/src/extra/themes/basic \
LVGL/lvgl/src/extra/themes/default \
LVGL/lvgl/src/extra/themes/mono \
LVGL/lvgl/src/extra/widgets/analogclock \
LVGL/lvgl/src/extra/widgets/animimg \
LVGL/lvgl/src/extra/widgets/calendar \
LVGL/lvgl/src/extra/widgets/carousel \
LVGL/lvgl/src/extra/widgets/chart \
LVGL/lvgl/src/extra/widgets/colorwheel \
LVGL/lvgl/src/extra/widgets/dclock \
LVGL/lvgl/src/extra/widgets/imgbtn \
LVGL/lvgl/src/extra/widgets/keyboard \
LVGL/lvgl/src/extra/widgets/led \
LVGL/lvgl/src/extra/widgets/list \
LVGL/lvgl/src/extra/widgets/menu \
LVGL/lvgl/src/extra/widgets/meter \
LVGL/lvgl/src/extra/widgets/msgbox \
LVGL/lvgl/src/extra/widgets/radiobtn \
LVGL/lvgl/src/extra/widgets/span \
LVGL/lvgl/src/extra/widgets/spinbox \
LVGL/lvgl/src/extra/widgets/spinner \
LVGL/lvgl/src/extra/widgets/tabview \
LVGL/lvgl/src/extra/widgets/textprogress \
LVGL/lvgl/src/extra/widgets/tileview \
LVGL/lvgl/src/extra/widgets/video \
LVGL/lvgl/src/extra/widgets/win \
LVGL/lvgl/src/font \
LVGL/lvgl/src/hal \
LVGL/lvgl/src/misc \
LVGL/lvgl/src/widgets \
LVGL/lvgl/tests/makefile \
LVGL/lvgl/tests/src \
LVGL/lvgl/tests/src/test_cases \
LVGL/lvgl/tests/src/test_fonts \
LVGL/lvgl/tests/unity \

